version: "3"

services:

  dss:
    image: redis:7.0.5
    restart: always
    networks:
      - backend
    volumes:
      - 'redis:/var/lib/redis/data'
    command: redis-server

  db:
    image: postgres:14.5
    restart: always
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - '5432:5432'

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/dev.conf:/etc/nginx/nginx.conf
    tty: true
    depends_on:
      dss:
        condition: service_started
      db:
        condition: service_healthy
      hub:
        condition: service_started

  hub:
    stdin_open: true
    tty: true
    depends_on:
      - db
      - dss
    restart: unless-stopped
    build:
      context: ./hub
      dockerfile: ./Dockerfile
    volumes:
      - ./hub:/hub
    networks:
      - backend
    ports:
      - "80:3000" # maps port 80 on the host machine to port 3000 on the container (visit at http://localhost/)
    command: rails server -b 0.0.0.0 -p 3000

networks:
  backend:

volumes:
  postgres:
  redis:
